### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by otofoto** [haicen/DahuaHashCreator#1]
Script doesn't run on Python 2.7

Traceback (most recent call last):
  File "C:\Utils\python\DahuaHash.py", line 103, in <module>
    main()
  File "C:\Utils\python\DahuaHash.py", line 87, in main
    print("{} = {}".format(arg,dhash(arg)))
  File "C:\Utils\python\DahuaHash.py", line 56, in dhash
    compressor(crypt,out2)
  File "C:\Utils\python\DahuaHash.py", line 27, in compressor
    out[j] = (in_var[i] + in_var[i+1]) % 62;
TypeError: not all arguments converted during string formatting

**Comment by brandon9vt** [comment]
I never actually tested this on earlier versions, so sorry for the confusion. The issue is how python 2.x handles bytestring objects. In 2.x they are stored as a string, and in 3.x stored as an integer.

I can't devote any time to work on this in the next couple weeks. I'd suggest upgrading to python 3 if possible.

**Comment by davidak501** [comment]
I found quick solution for this issue. Hope it will help someone.

It looks like Python 2.7 doesn't work with chars as numbers, so they has to be converted. It is done with function ord().

You have to add this function only to line 27 like this.
out[j] = (ord(in_var[i]) + ord(in_var[i+1])) % 62;

That should be all.

**Comment by brandon9vt** [comment]
Thanks. I wasn't too concerned about trying to fix this for python 2 since it is on it's way out, and honestly I've forgotten about it. I have tested and added your fix.
