### ISSUE TITLE
Dahua, unable to crack it with john 

### ISSUE THREAD

**Issue by Jugulaire** [haicen/DahuaHashCreator#2]
Hey dude, 

Currently i'm trying to break some Dahua hash but i got a problem. 

When i try to crack Dahua with John it is not working.
Is your Dahua format malformed ? 

Here is my command : 

~~~
root@kali:~/carrier# john --wordlist /usr/share/wordlists/rockyou.txt hash.txt --format=dahua
Warning: invalid UTF-8 seen reading /usr/share/wordlists/rockyou.txt
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
~~~

And the content of hash.txt : 

~~~
check:cXVhZ2dh
~~~

**Comment by brandon9vt** [comment]
A couple of things are wrong here.

1) the format of your input file needs to be 
`$dahua$hash`

so for your example:
`$dahua$cXVhZ2dh`

2) generally for DVR systems, the password is 4-8 characters consisting of numbers 0-9. On the units I've tested, just an on-screen keypad opens since there is no physical keyboard. In case you are curious, plugging a usb keyboard in does not work, at least on mine.

3) with the assumptions above, you would be better off trying 
`./john --format=dahua --incremental:Digits --max-len=8 <your hash list>`

I ran the above option and did not get a decode either, so either the hash is incorrect, or it isn't really a dahua. Is the length of the hash always the same no matter how many characters are in the cleartext?

For example, if you change your hash list to be
`$dahua$nTBCS19C`

you should get 123456 back as the password.

**Comment by csenger18** [comment]
Will you create a script to create new type of hash?
